version: 2
jobs:
  setup-environment:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/front-end
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths: ./front-end

  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build front-end
          command: cd front-end && npm run build

  e2e-test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Fetch Meta repository and clone back-end
          command: git clone https://github.com/C4SolutionsTDDC88/c4solutions.git && cd ~/project/c4solutions && git clone https://github.com/C4SolutionsTDDC88/back-end.git
      - attach_workspace:
          at: ~/
      - run:
          name: move front-end code
          command: mkdir ~/project/c4solutions/front-end && sudo mv ~/front-end/* ~/project/c4solutions/front-end/
      - setup_remote_docker
      - run:
          name: run test
          command: cd c4solutions && npm install && npm run start

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup-environment
      - build:
          requires:
            - setup-environment
      - e2e-test:
          requires:
            - setup-environment 